### PR TITLE
Rewrite site using WebC

### LINKED ISSUE #81: Contents navigator on blog posts
Logging this one here but it's BIG and so more for me to remember that I want rather than actually something backloggy for now. I even created a new label for it. 

Essentially I just reviewed another portfolio and was stressed by the length of it and the inability to quickly browse through it. So this feature would be amazing. I found this for inspiration: 

https://fac-annual-report-2020.netlify.app/

Probably done by some 10x dev. 

I already did some [designs for it back in the day](https://www.figma.com/file/9zqbBlzOKDCOZp5s1Yribk/2021-Portfolio?node-id=301%3A41). Maybe we can get together for another sesh if this is gonna happen as it's a big one.

### PR DESCRIPTION
**Pull request by oliverjam**
This makes the code way simpler/cleaner/more organised. Everything is pretty much just normal HTML/CSS now too so hopefully slightly more accessible.

@Jamchiller I _think_ everything should be the same, but please have a look at the preview deployment and double-check I didn't break something. The only real change should be slight shifts in alignment/padding on some pages as the old site had weird random numbers that were a few pixels out in some cases.

Also implements table of contents

Fix #81

### CODE REVIEW

**Comment by Jamchiller** [comment]
Dammmn you somehow fixed the space between the intro text and content below it!!! Nice 👍 

I've had a look through and there's a few broken bits: 

- [ ] The contents functionality seems to only work when all images on the page are loaded, which for me (maybe because I don't have good internet) takes up to 10 seconds. This is most obvious when you've used an anchor link, because it just sits there at the top for a while and then finally shoots you down to the anchor link. Have a look at [this link ](https://deploy-preview-89--jaredhill-v2.netlify.app/work/standard-bank/#synthesising-the-initial-research) with a clear cache. 
- [x] On mobile, both Blog posts and work posts overflow past the screen 
- [ ] On desktop, blog posts that don't have the contents aren't centrally aligned 
- [x] Can you change the contents typeface to H5? Should hopefully look a bit nicer. 

Thanks man, hopefully none of these are too tricky...

**Comment by oliverjam** [comment]
Ok fixed the overflow and non-centering, they were the same root cause. I'll update the text styles in a minute once I manage to get back to the Figma to see what h5 is 😅 

I cannot replicate the loading issue. What exactly do you mean by the contents functionality not working? The actual nav links are present from the start and should be usable straight away since they don't require JS to load. The only thing that might be slow to work is the underline of the active link, since that does need JS.

When I load the in-page link you used with my network throttled to 3G it still jumps to the right section straight away. However as the images above load in it does get pushed down offscreen, which is kind of unavoidable since the images will always appear later.

**Comment by Jamchiller** [comment]
Re: h5 - it's also defined [here](https://jaredhill.co/blog/test-blog-piece/), on the test-blog-piece page, if that helps. It's the same style as the top nav next to the logo. 

I'll try replicate the issue with the loading.

**Comment by Jamchiller** [comment]
Actually I'm getting this error when I try to go on the Deploy Preview.
Screenshot 2022-12-07 at 12 08 55

**Comment by oliverjam** [comment]
Ah right that's why I was confused lol, `h5`s don't have any styles specified except using Lato as the font. Speaking of which, super weird but although Figma and the site are both using Lato 700 weight the site looks _way_ bolder

## Figma

Screenshot 2022-12-07 at 18 10 15

## Site

Screenshot 2022-12-07 at 18 11 08

**Comment by Jamchiller** [comment]
Yeah the font weight thing is fucking weird. Could you manually reduce the font weight a fraction, or would that be hacky? 

I've got access now so will try to capture the issues

**Comment by oliverjam** [comment]
This is Lato 600—looks closer to the designs to me

Screenshot 2022-12-07 at 18 17 47

**Comment by Jamchiller** [comment]
Yep, that looks way better!

**Comment by Jamchiller** [comment]
Okay well I reckon adjust the H5 thing and then this boy is good to go!!! I just need to use more optimised images I reckon, solves the problem.

**Comment by oliverjam** [comment]
Pretty sure the styles match the Figma mockups now.

And yeah, some of those Medium images are like 6MB each 😬. [ImageOptim](https://imageoptim.com/mac) is your friend

**Comment by Jamchiller** [comment]
Styles haven't seemed to have changed for me? Image below

And yeah definitely, I was super lazy with it when doing it in Medium. 


Screenshot 2022-12-07 at 12 35 45

**Comment by oliverjam** [comment]
Oh I forgot to push lol. Should be deploying momentarily

**Comment by Jamchiller** [comment]
Uh oh, it looks like that deploy brought back the other two problems (copying here): 
- [ ]  On mobile, both Blog posts and work posts overflow past the screen
- [ ]  On desktop, blog posts that don't have the contents aren't centrally aligned

Also, looking at the contents, it doesn't look like the size is H5, is it H4? It's bigger than the text in the top nav. 

If it goes down to H5, the spacing between each list item might need to be reduced a bit too.

**Comment by oliverjam** [comment]
Sorry not sure how I broke that. Should be fine now.

The Figma mockup had the table of contents links at 20px so I copied that. I've dropped them down to 16px to match the nav and reduced the gap between slightly.

**Comment by Jamchiller** [comment]
Love it 🎟️ 🎟️ 🎟️ 🎟️ 🎟️ 🎟️ 🎟️ 🎟️ 🎟️ 🎟️ 🎟️ 🎟️

**Pull request merged**
